name: "Release 1 - Initial New Release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version you want to release."
        required: true
        default: "1.0.0"

jobs:
  prepare-release:
    name: "Prepare and push new release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Bump version in package.json
        run: yarn version --new-version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Commit version bump and push to develop
        id: commit-version-bump
        run: |
          git add package.json
          git commit -m "Bump version to ${{ github.event.inputs.version }}"
          git push origin develop

      - name: Create release branch from develop
        run: |
          git checkout -b release/${{ github.event.inputs.version }}
          git push origin release/${{ github.event.inputs.version }}

      - name: Create pull request to master
        uses: thomaseizinger/create-pull-request@1.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: release/${{ github.event.inputs.version }}
          base: master
          title: "Release version ${{ github.event.inputs.version }}"
          reviewers: ${{ github.actor }}
          body: |
            Hi @${{ github.actor }}!

            This PR was created for releasing version ${{ github.event.inputs.version }}.
            Merging this PR to master will trigger the release publication.
